// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcH8tdPzUSnlNKf1tUbY1YpYRawiaPwqk',
    appId: '1:734425711866:web:5d40d0003974fee7aff543',
    messagingSenderId: '734425711866',
    projectId: 'e-support-ec55b',
    authDomain: 'e-support-ec55b.firebaseapp.com',
    storageBucket: 'e-support-ec55b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAPlAKdeZeWAb5TtGIq2EHPn3Ch-pX68',
    appId: '1:734425711866:android:4ecea1ecf1d2a489aff543',
    messagingSenderId: '734425711866',
    projectId: 'e-support-ec55b',
    storageBucket: 'e-support-ec55b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPhWhDns56ZYZkZjJ1czdvWfuf7pzN2M',
    appId: '1:734425711866:ios:da2267ceba2f30cbaff543',
    messagingSenderId: '734425711866',
    projectId: 'e-support-ec55b',
    storageBucket: 'e-support-ec55b.appspot.com',
    iosClientId: '734425711866-hm0ucl22m0orueua7ojmcp176vgo8ij4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eSupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfPhWhDns56ZYZkZjJ1czdvWfuf7pzN2M',
    appId: '1:734425711866:ios:da2267ceba2f30cbaff543',
    messagingSenderId: '734425711866',
    projectId: 'e-support-ec55b',
    storageBucket: 'e-support-ec55b.appspot.com',
    iosClientId: '734425711866-hm0ucl22m0orueua7ojmcp176vgo8ij4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eSupport',
  );
}
